name: osdev4arab
author: a3f
baseurl: /herring-cove
description: نحو مجتمع عربي عن تطوير نظم التشغيل
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: ahmad@a3f.at
location: $HOME
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
