name: OSDev4Arab
author: OSDev4Arab
domain: a3f.at
baseurl: /blog
description: نحو مجتمع عربي عن تطوير نظم التشغيل
github: http://www.github.com/osdev4arab/osdev4arab
twitter: http://www.twitter.com/
facebook: https://www.facebook.com/groups/osdev4arab/
linkedin: http://www.linkedin.com
email: osdev4arab@gmail.com 
location: $HOME
disqus: osdev4arab 
##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
